[font]

normal.family = "Inconsolata Nerd Font Mono"
bold.family = "Inconsolata Nerd Font Mono"
italic.family = "Inconsolata Nerd Font Mono"
bold_italic.family = "Inconsolata Nerd Font Mono"

size = 8.0
