[window]
padding = {x = 10, y = 10}
decorations = "Full"
opacity = 1.0
dynamic_title = true

[font]
size = 8.5

[font.normal]
family = "FiraCode Nerd Font Mono"

# Normal colors
[colors.normal]
black = "0x26233a"
red = "0xeb6f92"
green = "0x9ccfd8"
yellow = "0xf6c177"
blue = "0x31748f"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"

# Bright colors
[colors.bright]
black = "0x6e6a86"
red = "0xeb6f92"
green = "0x9ccfd8"
yellow = "0xf6c177"
blue = "0x31748f"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"

[colors.primary]
background = "#000000"
foreground = "#f8f8f2"

[colors.cursor]
text = "#000000"
cursor = "#ff0000"

