[window]
padding = {x = 5, y = 2}
decorations = "Full"
opacity = 1.0
dynamic_title = true

[font]
normal = {family = 'Fixedsys Excelsior', style = "Regular"}
bold = {family = 'Fixedsys Excelsior', style = "Regular"}
italic = {family = 'Fixedsys Excelsior', style = "Regular"}
bold_italic = {family = 'Fixedsys Excelsior', style = "Regular"}
#normal = {family = 'IosevkaTerm Nerd Font'}
size = 6.5

# Colors (Solarized Dark)

# Default colors
[colors.primary]
background = "0x002b36"
foreground = "0x839496"

# Normal colors
[colors.normal]
black = "0x073642"
red = "0xdc322f"
green = "0x859900"
yellow = "0xb58900"
blue = "0x268bd2"
magenta = "0xd33682"
cyan = "0x2aa198"
white = "0xeee8d5"

# Bright colors
[colors.bright]
black = "0x002b36"
red = "0xcb4b16"
green = "0x586e75"
yellow = "0x657b83"
blue = "0x839496"
magenta = "0x6c71c4"
cyan = "0x93a1a1"
white = "0xfdf6e3"
